In [1]:
import sys
from pathlib import Path
import json
from datasets import load_dataset
import torch
import torch.nn as nn
from torchvision.transforms import transforms
import torch.nn.init as init

In [2]:
# Thư mục gốc của project
ROOT_DIR = Path.cwd().parent
ROOT_DIR

WindowsPath('D:/Code Module 6/VietNamese_Image_Captioning_with_CNN_LTSM')

In [3]:
dataset = load_dataset("ai-enthusiasm-community/KTVIC")

In [4]:
dataset['train'][0]

{'image_uid': '000000000001',
 'caption_uid': ['000000000001_1',
  '000000000001_2',
  '000000000001_3',
  '000000000001_4',
  '000000000001_5'],
 'image': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=695x456>,
 'caption_vi': ['ba chiếc thuyền đang di chuyển ở trên con sông',
  'có ba con thuyền đang di chuyển trên con sông',
  'trên dòng sông có ba con thuyền đang di chuyển',
  'ba con thuyền đang di chuyển bên một cánh đồng lúa',
  'ba chiếc thuyền đang chuyển động trên một con sông'],
 'segment_caption_vi': ['ba chiếc thuyền đang di_chuyển ở trên con sông',
  'có ba con thuyền đang di_chuyển trên con sông',
  'trên dòng sông có ba con thuyền đang di_chuyển',
  'ba con thuyền đang di_chuyển bên một cánh đồng lúa',
  'ba chiếc thuyền đang chuyển_động trên một con sông']}

In [5]:
SOURCE_DIR = ROOT_DIR/'source'
MODEL_DIR = ROOT_DIR/'model'
CONFIG_DIR = ROOT_DIR/'configuration'

In [6]:
# Thêm các thư mục vào không gian tìm kiếm
sys.path.extend([str(ROOT_DIR), str(SOURCE_DIR), str(MODEL_DIR), str(CONFIG_DIR)])

In [7]:
len(dataset['train'])

3769

# Load vocab is built in file.json

In [8]:
from vocabulary.vocab import *

In [9]:
tokenizer = Tokenizer()

In [10]:
PATH_SAVE_VOCAB = CONFIG_DIR/'vocab.json'

In [11]:
vocab = BuiltVocabFromIterator()

In [12]:
vocab.load(path=str(PATH_SAVE_VOCAB))

In [13]:
vocab_size = vocab.vocab_size
vocab_size

2000

In [14]:
vocab.stoi()

{'<padd>': 0,
 '<start>': 1,
 '<end>': 2,
 '<unk>': 3,
 'có': 4,
 'một': 5,
 'ở': 6,
 'đang': 7,
 'người': 8,
 'xuất_hiện': 9,
 'trên': 10,
 'của': 11,
 'bên': 12,
 'trong': 13,
 'nhiều': 14,
 'chiếc': 15,
 'những': 16,
 'trước': 17,
 'phụ_nữ': 18,
 'màu': 19,
 'hàng': 20,
 'mặc': 21,
 'được': 22,
 'đứng': 23,
 'hai': 24,
 'gái': 25,
 'cô': 26,
 'phía': 27,
 'áo': 28,
 'sự': 29,
 'đàn_ông': 30,
 'đường': 31,
 'nhà': 32,
 'bức': 33,
 'là': 34,
 'quầy': 35,
 'cái': 36,
 'con': 37,
 'một_vài': 38,
 'ảnh': 39,
 'cửa_hàng': 40,
 'khu': 41,
 'và': 42,
 'ngồi': 43,
 'tay': 44,
 'đây': 45,
 'trắng': 46,
 'ngôi': 47,
 'di_chuyển': 48,
 'xanh': 49,
 'chụp': 50,
 'này': 51,
 'đi': 52,
 'xe_máy': 53,
 'siêu_thị': 54,
 'cây': 55,
 'đỏ': 56,
 'chợ': 57,
 'các': 58,
 'nhau': 59,
 'kệ': 60,
 'xe': 61,
 'cầm': 62,
 'đen': 63,
 'vào': 64,
 'khung_cảnh': 65,
 'lá': 66,
 'nhóm': 67,
 'trưng_bày': 68,
 'căn': 69,
 'bán': 70,
 'khu_vực': 71,
 'rau': 72,
 'hình': 73,
 'tường': 74,
 'đồ': 75,
 'quả': 76,
 'mặ

In [15]:
vocab.itos()

{0: '<padd>',
 1: '<start>',
 2: '<end>',
 3: '<unk>',
 4: 'có',
 5: 'một',
 6: 'ở',
 7: 'đang',
 8: 'người',
 9: 'xuất_hiện',
 10: 'trên',
 11: 'của',
 12: 'bên',
 13: 'trong',
 14: 'nhiều',
 15: 'chiếc',
 16: 'những',
 17: 'trước',
 18: 'phụ_nữ',
 19: 'màu',
 20: 'hàng',
 21: 'mặc',
 22: 'được',
 23: 'đứng',
 24: 'hai',
 25: 'gái',
 26: 'cô',
 27: 'phía',
 28: 'áo',
 29: 'sự',
 30: 'đàn_ông',
 31: 'đường',
 32: 'nhà',
 33: 'bức',
 34: 'là',
 35: 'quầy',
 36: 'cái',
 37: 'con',
 38: 'một_vài',
 39: 'ảnh',
 40: 'cửa_hàng',
 41: 'khu',
 42: 'và',
 43: 'ngồi',
 44: 'tay',
 45: 'đây',
 46: 'trắng',
 47: 'ngôi',
 48: 'di_chuyển',
 49: 'xanh',
 50: 'chụp',
 51: 'này',
 52: 'đi',
 53: 'xe_máy',
 54: 'siêu_thị',
 55: 'cây',
 56: 'đỏ',
 57: 'chợ',
 58: 'các',
 59: 'nhau',
 60: 'kệ',
 61: 'xe',
 62: 'cầm',
 63: 'đen',
 64: 'vào',
 65: 'khung_cảnh',
 66: 'lá',
 67: 'nhóm',
 68: 'trưng_bày',
 69: 'căn',
 70: 'bán',
 71: 'khu_vực',
 72: 'rau',
 73: 'hình',
 74: 'tường',
 75: 'đồ',
 76: 'quả',
 77:

In [16]:
vocab.default_key

'<unk>'

# Lấy thông số của mean và std để normalize ảnh đã được lưu trong file.json

In [17]:
from preprocessing.preprocessing_img import*

In [18]:
computer = ComputeMeanStd()

In [19]:
mean_std_path = CONFIG_DIR/'mean_std_img.json'

In [20]:
mean, std = computer.load_mean_std(str(mean_std_path))

In [21]:
print(mean)
print(std)

tensor([0.5003, 0.4708, 0.4325])
tensor([0.2772, 0.2680, 0.2803])


# Khởi tạo kiểu DL vicaptionDatset đã được xây dựng

In [22]:
from organize_data import * 

In [23]:
vicaptiondataset = VicaptioningDataSet(dataset= dataset, split='train',
                                       val_split=0.1,
                                       transform=[transforms.Normalize(mean= mean, std=std),
                                                 transforms.RandomErasing(p=0.3, scale=(0.02, 0.15),ratio = (0.3, 0.3), value = 0)],
                                       max_length=30, vocab=vocab)

In [24]:
vicaption_valdataset =VicaptioningDataSet(dataset= dataset, split='valid', val_split=0.1, transform=[transforms.Normalize(mean= mean, std=std)], max_length=30, vocab=vocab)

In [25]:
len(vicaptiondataset)

16952

In [26]:
len(vicaption_valdataset)

377

In [27]:
vicaption_valdataset[376]

(tensor([[[ 1.1519,  1.1661,  1.1519,  ..., -0.1781, -0.3054, -0.2771],
          [ 1.1236,  1.0812,  1.0953,  ..., -0.2630, -0.4894, -0.3903],
          [ 0.9821,  0.9397,  1.0387,  ..., -0.2347, -0.4894, -0.3620],
          ...,
          [ 0.7275, -0.5601, -0.1639,  ...,  1.2651,  1.5481,  1.5906],
          [ 0.1049, -0.6733,  0.0200,  ...,  1.5340,  1.5623,  1.5623],
          [-0.1073, -0.3620,  0.2747,  ...,  1.5623,  1.5481,  1.5623]],
 
         [[ 1.2719,  1.3011,  1.2573,  ...,  0.0283, -0.0448, -0.0302],
          [ 1.2719,  1.2280,  1.2280,  ..., -0.0887, -0.2643, -0.1472],
          [ 1.1695,  1.0963,  1.1841,  ..., -0.1180, -0.3228, -0.1472],
          ...,
          [ 0.4526, -0.8056, -0.2935,  ...,  1.5352,  1.7693,  1.7839],
          [-0.2496, -0.9226, -0.0302,  ...,  1.7986,  1.8278,  1.8278],
          [-0.4837, -0.5861,  0.2332,  ...,  1.8132,  1.8278,  1.8132]],
 
         [[ 1.1852,  1.2131,  1.1712,  ..., -0.4937, -0.5777, -0.7176],
          [ 1.2131,  1.1852,

In [28]:
X_train, y_train, y_ = vicaptiondataset[0]

In [29]:
X_train

tensor([[[0.0342, 0.0766, 0.1332,  ..., 0.9397, 0.9538, 0.9538],
         [0.0342, 0.0483, 0.1049,  ..., 0.8690, 0.8548, 0.8831],
         [0.1332, 0.1191, 0.1615,  ..., 0.8265, 0.7841, 0.7982],
         ...,
         [0.7133, 0.6709, 0.6850,  ..., 0.7982, 0.7982, 0.8265],
         [0.7133, 0.6850, 0.6992,  ..., 0.7982, 0.8265, 0.8690],
         [0.7275, 0.7699, 0.7275,  ..., 0.8124, 0.8407, 0.8972]],

        [[0.9500, 0.9793, 0.9939,  ..., 1.5937, 1.5937, 1.6084],
         [0.9500, 0.9500, 0.9647,  ..., 1.5352, 1.5352, 1.5645],
         [1.0085, 0.9939, 1.0085,  ..., 1.5352, 1.5060, 1.5206],
         ...,
         [0.7306, 0.6867, 0.7452,  ..., 0.9354, 0.9208, 0.9500],
         [0.7306, 0.7013, 0.7452,  ..., 0.9354, 0.9500, 0.9939],
         [0.7452, 0.7891, 0.7745,  ..., 0.9500, 0.9647, 1.0232]],

        [[1.5909, 1.6049, 1.5909,  ..., 1.7868, 1.7868, 1.8008],
         [1.5769, 1.5629, 1.5629,  ..., 1.7448, 1.7308, 1.7588],
         [1.6049, 1.5769, 1.5769,  ..., 1.7588, 1.7168, 1.

In [30]:
y_train

tensor([  1, 101,  15,  88,   7,  48,   6,  10,  37, 110,   2,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0])

In [31]:
y_

tensor([101,  15,  88,   7,  48,   6,  10,  37, 110,   2,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0])

In [32]:
X_train.shape

torch.Size([3, 224, 224])

In [33]:
y_train.shape

torch.Size([29])

In [34]:
y_.shape

torch.Size([29])

# Khởi tạo mô hình và huấn luyện mô hình ViCaptioningImgModel

In [35]:
vocab.vocab_size

2000

In [36]:
from build_model import *

In [37]:
ModelGenerateCaption = ViCaptioningImgModel(version_ResNet=18, vocab_size=vocab.vocab_size, embedding_dim=1024,hidden_size=1024,num_layer_LSTM=4)

In [38]:
list(ModelGenerateCaption.modules())

[ViCaptioningImgModel(
   (encoder): ViCaptionEncoder(
     (model): Sequential(
       (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
       (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
       (2): ReLU(inplace=True)
       (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
       (4): Sequential(
         (0): BasicBlock(
           (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
           (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
           (relu): ReLU(inplace=True)
           (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
           (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
         )
         (1): BasicBlock(
           (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), 

In [39]:
init.xavier_normal_(ModelGenerateCaption.LinearF2c0.weight)
init.xavier_normal_(ModelGenerateCaption.LinearF2h0.weight)
init.zeros_(ModelGenerateCaption.LinearF2c0.bias)
init.zeros_(ModelGenerateCaption.LinearF2h0.bias)

Parameter containing:
tensor([0., 0., 0.,  ..., 0., 0., 0.], requires_grad=True)

In [40]:
Trainer = TrainModel()

In [41]:
criterion = nn.CrossEntropyLoss(ignore_index=vocab.vocab['<padd>'])

In [42]:
optimizer = torch.optim.Adam([
    {'params': ModelGenerateCaption.encoder.parameters(), 'lr': 1e-5},
    {'params': ModelGenerateCaption.decoder.parameters(), 'lr': 1e-3},
    {'params': ModelGenerateCaption.LinearF2h0.parameters(), 'lr': 1e-3},
    {'params': ModelGenerateCaption.LinearF2c0.parameters(), 'lr': 1e-3},
], weight_decay=0.0001)

In [43]:
scheduler = torch.optim.lr_scheduler.StepLR(optimizer=optimizer, gamma=0.3, step_size=30)

In [44]:
Trainer.fit(model=ModelGenerateCaption,
            n_epochs=100,
            batch_size=256,
            criterion=criterion,
            optimizer= optimizer,
            dataset=vicaptiondataset,
            val_dataset=vicaption_valdataset,
            idx_padd=vocab.vocab['<padd>'],
            is_shuffle=True,
            max_length=30,
            scheduler=scheduler,
            vocab=vocab)

  1%|▊                                                                              | 1/100 [02:24<3:58:32, 144.57s/it]

Epoch [   1/ 100]  - Loss = 4.7587 - Accuracy = 0.1931
BLEU1  = 0.5008 - BLEU2 = 0.3264 - BLEU3 = 0.1918 - BLEU4 =0.1173


  2%|█▌                                                                             | 2/100 [04:40<3:47:26, 139.25s/it]

Epoch [   2/ 100]  - Loss = 3.9283 - Accuracy = 0.2794
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


  3%|██▎                                                                            | 3/100 [06:57<3:43:50, 138.45s/it]

Epoch [   3/ 100]  - Loss = 2.9733 - Accuracy = 0.3957
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


  4%|███▏                                                                           | 4/100 [09:16<3:41:54, 138.69s/it]

Epoch [   4/ 100]  - Loss = 2.5527 - Accuracy = 0.4456
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


  5%|███▉                                                                           | 5/100 [11:31<3:37:19, 137.26s/it]

Epoch [   5/ 100]  - Loss = 2.3158 - Accuracy = 0.4788
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


  6%|████▋                                                                          | 6/100 [13:46<3:33:50, 136.50s/it]

Epoch [   6/ 100]  - Loss = 2.1574 - Accuracy = 0.5002
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


  7%|█████▌                                                                         | 7/100 [16:01<3:31:00, 136.13s/it]

Epoch [   7/ 100]  - Loss = 2.0319 - Accuracy = 0.5186
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


  8%|██████▎                                                                        | 8/100 [18:17<3:28:22, 135.90s/it]

Epoch [   8/ 100]  - Loss = 1.9326 - Accuracy = 0.5337
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


  9%|███████                                                                        | 9/100 [20:31<3:25:28, 135.48s/it]

Epoch [   9/ 100]  - Loss = 1.8460 - Accuracy = 0.5478
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 10%|███████▊                                                                      | 10/100 [22:46<3:22:55, 135.29s/it]

Epoch [  10/ 100]  - Loss = 1.7611 - Accuracy = 0.5614
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 11%|████████▌                                                                     | 11/100 [25:13<3:25:44, 138.70s/it]

Epoch [  11/ 100]  - Loss = 1.6938 - Accuracy = 0.5735
BLEU1  = 0.6262 - BLEU2 = 0.4722 - BLEU3 = 0.3443 - BLEU4 =0.2515


 12%|█████████▎                                                                    | 12/100 [27:30<3:22:48, 138.28s/it]

Epoch [  12/ 100]  - Loss = 1.6299 - Accuracy = 0.5856
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 13%|██████████▏                                                                   | 13/100 [29:49<3:21:02, 138.65s/it]

Epoch [  13/ 100]  - Loss = 1.5674 - Accuracy = 0.5968
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 14%|██████████▉                                                                   | 14/100 [32:06<3:17:39, 137.91s/it]

Epoch [  14/ 100]  - Loss = 1.5043 - Accuracy = 0.6087
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 15%|███████████▋                                                                  | 15/100 [34:39<3:21:49, 142.47s/it]

Epoch [  15/ 100]  - Loss = 1.4620 - Accuracy = 0.6168
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 16%|████████████▍                                                                 | 16/100 [37:12<3:24:06, 145.80s/it]

Epoch [  16/ 100]  - Loss = 1.4057 - Accuracy = 0.6297
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 17%|█████████████▎                                                                | 17/100 [39:30<3:18:32, 143.52s/it]

Epoch [  17/ 100]  - Loss = 1.3536 - Accuracy = 0.6402
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 18%|██████████████                                                                | 18/100 [41:46<3:12:52, 141.12s/it]

Epoch [  18/ 100]  - Loss = 1.3164 - Accuracy = 0.6480
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 19%|██████████████▊                                                               | 19/100 [44:01<3:08:03, 139.30s/it]

Epoch [  19/ 100]  - Loss = 1.2708 - Accuracy = 0.6587
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 20%|███████████████▌                                                              | 20/100 [46:16<3:04:11, 138.14s/it]

Epoch [  20/ 100]  - Loss = 1.2360 - Accuracy = 0.6659
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 21%|████████████████▍                                                             | 21/100 [48:42<3:04:40, 140.25s/it]

Epoch [  21/ 100]  - Loss = 1.1950 - Accuracy = 0.6756
BLEU1  = 0.6115 - BLEU2 = 0.4585 - BLEU3 = 0.3374 - BLEU4 =0.2503


 22%|█████████████████▏                                                            | 22/100 [50:59<3:01:02, 139.26s/it]

Epoch [  22/ 100]  - Loss = 1.1570 - Accuracy = 0.6840
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 23%|█████████████████▉                                                            | 23/100 [53:14<2:57:17, 138.15s/it]

Epoch [  23/ 100]  - Loss = 1.1226 - Accuracy = 0.6922
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 24%|██████████████████▋                                                           | 24/100 [55:29<2:53:35, 137.05s/it]

Epoch [  24/ 100]  - Loss = 1.0937 - Accuracy = 0.6974
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 25%|███████████████████▌                                                          | 25/100 [57:44<2:50:52, 136.69s/it]

Epoch [  25/ 100]  - Loss = 1.0723 - Accuracy = 0.7040
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 26%|███████████████████▊                                                        | 26/100 [1:00:00<2:48:03, 136.26s/it]

Epoch [  26/ 100]  - Loss = 1.0387 - Accuracy = 0.7111
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 27%|████████████████████▌                                                       | 27/100 [1:02:16<2:45:45, 136.24s/it]

Epoch [  27/ 100]  - Loss = 1.0116 - Accuracy = 0.7186
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 28%|█████████████████████▎                                                      | 28/100 [1:04:32<2:43:20, 136.12s/it]

Epoch [  28/ 100]  - Loss = 0.9885 - Accuracy = 0.7241
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 29%|██████████████████████                                                      | 29/100 [1:07:14<2:50:29, 144.07s/it]

Epoch [  29/ 100]  - Loss = 0.9694 - Accuracy = 0.7274
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 30%|██████████████████████▊                                                     | 30/100 [1:09:35<2:46:47, 142.97s/it]

Epoch [  30/ 100]  - Loss = 0.9511 - Accuracy = 0.7319
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 31%|███████████████████████▌                                                    | 31/100 [1:12:02<2:45:53, 144.26s/it]

Epoch [  31/ 100]  - Loss = 0.7892 - Accuracy = 0.7770
BLEU1  = 0.6181 - BLEU2 = 0.4525 - BLEU3 = 0.3245 - BLEU4 =0.2407


 32%|████████████████████████▎                                                   | 32/100 [1:14:20<2:41:15, 142.29s/it]

Epoch [  32/ 100]  - Loss = 0.7299 - Accuracy = 0.7919
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 33%|█████████████████████████                                                   | 33/100 [1:16:37<2:37:06, 140.70s/it]

Epoch [  33/ 100]  - Loss = 0.7100 - Accuracy = 0.7984
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 34%|█████████████████████████▊                                                  | 34/100 [1:18:53<2:33:14, 139.32s/it]

Epoch [  34/ 100]  - Loss = 0.6944 - Accuracy = 0.8026
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 35%|██████████████████████████▌                                                 | 35/100 [1:21:07<2:29:12, 137.73s/it]

Epoch [  35/ 100]  - Loss = 0.6834 - Accuracy = 0.8062
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 36%|███████████████████████████▎                                                | 36/100 [1:23:21<2:25:42, 136.60s/it]

Epoch [  36/ 100]  - Loss = 0.6721 - Accuracy = 0.8091
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 37%|████████████████████████████                                                | 37/100 [1:25:35<2:22:50, 136.04s/it]

Epoch [  37/ 100]  - Loss = 0.6613 - Accuracy = 0.8119
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 38%|████████████████████████████▉                                               | 38/100 [1:27:51<2:20:31, 135.99s/it]

Epoch [  38/ 100]  - Loss = 0.6526 - Accuracy = 0.8144
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 39%|█████████████████████████████▋                                              | 39/100 [1:30:06<2:17:44, 135.49s/it]

Epoch [  39/ 100]  - Loss = 0.6442 - Accuracy = 0.8161
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 40%|██████████████████████████████▍                                             | 40/100 [1:32:21<2:15:20, 135.34s/it]

Epoch [  40/ 100]  - Loss = 0.6426 - Accuracy = 0.8169
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 41%|███████████████████████████████▏                                            | 41/100 [1:34:45<2:15:50, 138.14s/it]

Epoch [  41/ 100]  - Loss = 0.6304 - Accuracy = 0.8205
BLEU1  = 0.5906 - BLEU2 = 0.4203 - BLEU3 = 0.2924 - BLEU4 =0.2082


 42%|███████████████████████████████▉                                            | 42/100 [1:37:02<2:13:04, 137.67s/it]

Epoch [  42/ 100]  - Loss = 0.6236 - Accuracy = 0.8218
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 43%|████████████████████████████████▋                                           | 43/100 [1:39:18<2:10:12, 137.06s/it]

Epoch [  43/ 100]  - Loss = 0.6189 - Accuracy = 0.8231
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 44%|█████████████████████████████████▍                                          | 44/100 [1:41:38<2:08:53, 138.11s/it]

Epoch [  44/ 100]  - Loss = 0.6114 - Accuracy = 0.8240
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 45%|██████████████████████████████████▏                                         | 45/100 [1:43:57<2:06:42, 138.22s/it]

Epoch [  45/ 100]  - Loss = 0.5988 - Accuracy = 0.8276
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 46%|██████████████████████████████████▉                                         | 46/100 [1:46:19<2:05:40, 139.63s/it]

Epoch [  46/ 100]  - Loss = 0.5977 - Accuracy = 0.8282
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 47%|███████████████████████████████████▋                                        | 47/100 [1:48:37<2:02:45, 138.98s/it]

Epoch [  47/ 100]  - Loss = 0.5899 - Accuracy = 0.8303
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 48%|████████████████████████████████████▍                                       | 48/100 [1:50:55<2:00:11, 138.69s/it]

Epoch [  48/ 100]  - Loss = 0.5831 - Accuracy = 0.8323
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 49%|█████████████████████████████████████▏                                      | 49/100 [1:53:13<1:57:36, 138.35s/it]

Epoch [  49/ 100]  - Loss = 0.5766 - Accuracy = 0.8341
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 50%|██████████████████████████████████████                                      | 50/100 [1:55:34<1:56:03, 139.28s/it]

Epoch [  50/ 100]  - Loss = 0.5744 - Accuracy = 0.8338
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 51%|██████████████████████████████████████▊                                     | 51/100 [1:58:05<1:56:34, 142.74s/it]

Epoch [  51/ 100]  - Loss = 0.5672 - Accuracy = 0.8359
BLEU1  = 0.5850 - BLEU2 = 0.4253 - BLEU3 = 0.3033 - BLEU4 =0.2186


 52%|███████████████████████████████████████▌                                    | 52/100 [2:00:27<1:53:59, 142.50s/it]

Epoch [  52/ 100]  - Loss = 0.5634 - Accuracy = 0.8375
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 53%|████████████████████████████████████████▎                                   | 53/100 [2:02:46<1:50:57, 141.64s/it]

Epoch [  53/ 100]  - Loss = 0.5609 - Accuracy = 0.8377
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 54%|█████████████████████████████████████████                                   | 54/100 [2:05:03<1:47:25, 140.13s/it]

Epoch [  54/ 100]  - Loss = 0.5541 - Accuracy = 0.8392
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 55%|█████████████████████████████████████████▊                                  | 55/100 [2:07:19<1:44:06, 138.81s/it]

Epoch [  55/ 100]  - Loss = 0.5458 - Accuracy = 0.8412
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 56%|██████████████████████████████████████████▌                                 | 56/100 [2:09:34<1:41:07, 137.89s/it]

Epoch [  56/ 100]  - Loss = 0.5431 - Accuracy = 0.8414
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 57%|███████████████████████████████████████████▎                                | 57/100 [2:11:57<1:39:51, 139.33s/it]

Epoch [  57/ 100]  - Loss = 0.5376 - Accuracy = 0.8435
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 58%|████████████████████████████████████████████                                | 58/100 [2:14:15<1:37:18, 139.02s/it]

Epoch [  58/ 100]  - Loss = 0.5303 - Accuracy = 0.8456
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 59%|████████████████████████████████████████████▊                               | 59/100 [2:16:34<1:35:00, 139.03s/it]

Epoch [  59/ 100]  - Loss = 0.5278 - Accuracy = 0.8466
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 60%|█████████████████████████████████████████████▌                              | 60/100 [2:18:52<1:32:26, 138.65s/it]

Epoch [  60/ 100]  - Loss = 0.5200 - Accuracy = 0.8482
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 61%|██████████████████████████████████████████████▎                             | 61/100 [2:21:22<1:32:20, 142.06s/it]

Epoch [  61/ 100]  - Loss = 0.4644 - Accuracy = 0.8653
BLEU1  = 0.5944 - BLEU2 = 0.4343 - BLEU3 = 0.3144 - BLEU4 =0.2346


 62%|███████████████████████████████████████████████                             | 62/100 [2:23:37<1:28:35, 139.89s/it]

Epoch [  62/ 100]  - Loss = 0.4472 - Accuracy = 0.8700
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 63%|███████████████████████████████████████████████▉                            | 63/100 [2:25:52<1:25:20, 138.39s/it]

Epoch [  63/ 100]  - Loss = 0.4441 - Accuracy = 0.8702
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 64%|████████████████████████████████████████████████▋                           | 64/100 [2:28:06<1:22:17, 137.15s/it]

Epoch [  64/ 100]  - Loss = 0.4397 - Accuracy = 0.8710
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 65%|█████████████████████████████████████████████████▍                          | 65/100 [2:30:21<1:19:31, 136.33s/it]

Epoch [  65/ 100]  - Loss = 0.4361 - Accuracy = 0.8726
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 66%|██████████████████████████████████████████████████▏                         | 66/100 [2:32:35<1:16:53, 135.70s/it]

Epoch [  66/ 100]  - Loss = 0.4373 - Accuracy = 0.8722
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 67%|██████████████████████████████████████████████████▉                         | 67/100 [2:34:50<1:14:32, 135.52s/it]

Epoch [  67/ 100]  - Loss = 0.4355 - Accuracy = 0.8723
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 68%|███████████████████████████████████████████████████▋                        | 68/100 [2:37:05<1:12:12, 135.38s/it]

Epoch [  68/ 100]  - Loss = 0.4325 - Accuracy = 0.8730
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 69%|████████████████████████████████████████████████████▍                       | 69/100 [2:39:19<1:09:44, 134.99s/it]

Epoch [  69/ 100]  - Loss = 0.4311 - Accuracy = 0.8739
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 70%|█████████████████████████████████████████████████████▏                      | 70/100 [2:41:34<1:07:28, 134.94s/it]

Epoch [  70/ 100]  - Loss = 0.4318 - Accuracy = 0.8745
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 71%|█████████████████████████████████████████████████████▉                      | 71/100 [2:43:59<1:06:38, 137.87s/it]

Epoch [  71/ 100]  - Loss = 0.4306 - Accuracy = 0.8734
BLEU1  = 0.5771 - BLEU2 = 0.4077 - BLEU3 = 0.2895 - BLEU4 =0.2125


 72%|██████████████████████████████████████████████████████▋                     | 72/100 [2:46:14<1:03:59, 137.13s/it]

Epoch [  72/ 100]  - Loss = 0.4290 - Accuracy = 0.8735
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 73%|███████████████████████████████████████████████████████▍                    | 73/100 [2:48:28<1:01:16, 136.18s/it]

Epoch [  73/ 100]  - Loss = 0.4291 - Accuracy = 0.8749
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 74%|█████████████████████████████████████████████████████████▋                    | 74/100 [2:50:44<58:55, 135.98s/it]

Epoch [  74/ 100]  - Loss = 0.4260 - Accuracy = 0.8750
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 75%|██████████████████████████████████████████████████████████▌                   | 75/100 [2:52:59<56:38, 135.96s/it]

Epoch [  75/ 100]  - Loss = 0.4240 - Accuracy = 0.8752
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 76%|███████████████████████████████████████████████████████████▎                  | 76/100 [2:55:19<54:50, 137.12s/it]

Epoch [  76/ 100]  - Loss = 0.4223 - Accuracy = 0.8761
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 77%|████████████████████████████████████████████████████████████                  | 77/100 [2:57:39<52:51, 137.91s/it]

Epoch [  77/ 100]  - Loss = 0.4226 - Accuracy = 0.8759
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 78%|████████████████████████████████████████████████████████████▊                 | 78/100 [2:59:58<50:41, 138.26s/it]

Epoch [  78/ 100]  - Loss = 0.4218 - Accuracy = 0.8754
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 79%|█████████████████████████████████████████████████████████████▌                | 79/100 [3:02:14<48:10, 137.64s/it]

Epoch [  79/ 100]  - Loss = 0.4219 - Accuracy = 0.8759
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 80%|██████████████████████████████████████████████████████████████▍               | 80/100 [3:04:32<45:54, 137.74s/it]

Epoch [  80/ 100]  - Loss = 0.4204 - Accuracy = 0.8757
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 81%|███████████████████████████████████████████████████████████████▏              | 81/100 [3:06:59<44:30, 140.54s/it]

Epoch [  81/ 100]  - Loss = 0.4174 - Accuracy = 0.8765
BLEU1  = 0.5729 - BLEU2 = 0.4115 - BLEU3 = 0.2957 - BLEU4 =0.2190


 82%|███████████████████████████████████████████████████████████████▉              | 82/100 [3:09:14<41:35, 138.66s/it]

Epoch [  82/ 100]  - Loss = 0.4176 - Accuracy = 0.8767
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 83%|████████████████████████████████████████████████████████████████▋             | 83/100 [3:11:31<39:08, 138.17s/it]

Epoch [  83/ 100]  - Loss = 0.4169 - Accuracy = 0.8767
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 84%|█████████████████████████████████████████████████████████████████▌            | 84/100 [3:13:49<36:49, 138.12s/it]

Epoch [  84/ 100]  - Loss = 0.4111 - Accuracy = 0.8790
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 85%|██████████████████████████████████████████████████████████████████▎           | 85/100 [3:16:08<34:38, 138.58s/it]

Epoch [  85/ 100]  - Loss = 0.4131 - Accuracy = 0.8776
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 86%|███████████████████████████████████████████████████████████████████           | 86/100 [3:18:28<32:25, 139.00s/it]

Epoch [  86/ 100]  - Loss = 0.4126 - Accuracy = 0.8781
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 87%|███████████████████████████████████████████████████████████████████▊          | 87/100 [3:20:53<30:29, 140.77s/it]

Epoch [  87/ 100]  - Loss = 0.4132 - Accuracy = 0.8777
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 88%|████████████████████████████████████████████████████████████████████▋         | 88/100 [3:23:12<28:00, 140.03s/it]

Epoch [  88/ 100]  - Loss = 0.4093 - Accuracy = 0.8783
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 89%|█████████████████████████████████████████████████████████████████████▍        | 89/100 [3:25:30<25:35, 139.59s/it]

Epoch [  89/ 100]  - Loss = 0.4094 - Accuracy = 0.8790
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 90%|██████████████████████████████████████████████████████████████████████▏       | 90/100 [3:27:45<23:01, 138.16s/it]

Epoch [  90/ 100]  - Loss = 0.4074 - Accuracy = 0.8786
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 91%|██████████████████████████████████████████████████████████████████████▉       | 91/100 [3:30:22<21:34, 143.80s/it]

Epoch [  91/ 100]  - Loss = 0.3892 - Accuracy = 0.8845
BLEU1  = 0.5825 - BLEU2 = 0.4231 - BLEU3 = 0.3071 - BLEU4 =0.2296


 92%|███████████████████████████████████████████████████████████████████████▊      | 92/100 [3:32:41<18:59, 142.39s/it]

Epoch [  92/ 100]  - Loss = 0.3843 - Accuracy = 0.8861
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 93%|████████████████████████████████████████████████████████████████████████▌     | 93/100 [3:35:02<16:33, 141.87s/it]

Epoch [  93/ 100]  - Loss = 0.3835 - Accuracy = 0.8860
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 94%|█████████████████████████████████████████████████████████████████████████▎    | 94/100 [3:37:25<14:13, 142.31s/it]

Epoch [  94/ 100]  - Loss = 0.3871 - Accuracy = 0.8848
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 95%|██████████████████████████████████████████████████████████████████████████    | 95/100 [3:39:41<11:41, 140.38s/it]

Epoch [  95/ 100]  - Loss = 0.3820 - Accuracy = 0.8861
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 96%|██████████████████████████████████████████████████████████████████████████▉   | 96/100 [3:42:01<09:21, 140.41s/it]

Epoch [  96/ 100]  - Loss = 0.3809 - Accuracy = 0.8857
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 97%|███████████████████████████████████████████████████████████████████████████▋  | 97/100 [3:44:17<06:57, 139.08s/it]

Epoch [  97/ 100]  - Loss = 0.3791 - Accuracy = 0.8864
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 98%|████████████████████████████████████████████████████████████████████████████▍ | 98/100 [3:46:48<04:45, 142.68s/it]

Epoch [  98/ 100]  - Loss = 0.3787 - Accuracy = 0.8871
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


 99%|█████████████████████████████████████████████████████████████████████████████▏| 99/100 [3:49:15<02:23, 143.84s/it]

Epoch [  99/ 100]  - Loss = 0.3786 - Accuracy = 0.8869
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


100%|█████████████████████████████████████████████████████████████████████████████| 100/100 [3:52:00<00:00, 139.21s/it]

Epoch [ 100/ 100]  - Loss = 0.3782 - Accuracy = 0.8867
BLEU1  = nan - BLEU2 = nan - BLEU3 = nan - BLEU4 =nan


In [45]:
PATH_SAVE_WEIGHT = ROOT_DIR/'model_weight.pth'

In [46]:
# Lưu trọng số đã huấn luyện của mô hình 
torch.save(ModelGenerateCaption.state_dict(),PATH_SAVE_WEIGHT)